"""Toast notification — Error (generated by Transitions Demo).

Settings:
  Type: Error
  Position: Bottom-Right
  Easing: back_out
  Duration: 0.7s
"""
import time

from CTkToolTip import CTkToolTip
import customtkinter as ctk
from tkinter import font as tkfont


# --- easings ---

def back_out(t):
    if t >= 1:
        return 1.0
    s = 1.70158
    u = t - 1
    return 1 + (s + 1) * u ** 3 + s * u ** 2

def ease_in(t):
    return t * t * t

# --- helpers ---

def lerp(a, b, t):
    return a + (b - a) * t

# --- tween engine ---

class Tween:
    FRAME_MS = 16

    def __init__(self, widget, duration, easing, step, on_done=None):
        self.widget = widget
        self.duration = max(duration, 0.001)
        self.easing = easing
        self.step = step
        self.on_done = on_done
        self._start = None
        self._running = False

    def start(self):
        self._start = time.perf_counter()
        self._running = True
        self._tick()
        return self

    def _tick(self):
        if not self._running:
            return
        t = min(
            (time.perf_counter() - self._start) / self.duration, 1.0
        )
        self.step(self.easing(t))
        if t < 1.0:
            self.widget.after(self.FRAME_MS, self._tick)
        else:
            self._running = False
            if self.on_done:
                self.on_done()

# --- animation ---

import tkinter as tk

TOAST_MIN_W = 220
TOAST_MAX_W = 600
TOAST_H = 60
TOAST_MARGIN = 16
TOAST_SPACING = 8
TOAST_HOLD_MS = 2000
TOAST_SLIDE_OFFSET = 140
TOAST_HORIZONTAL_CHROME = 34

_toast_stacks = {}

def _toast_slot(parent, position, index, toast_w):
    parent.update_idletasks()
    win_x = parent.winfo_x()
    win_y = parent.winfo_y()
    win_w = parent.winfo_width()
    win_h = parent.winfo_height()

    if 'Right' in position:
        x = win_x + win_w - toast_w - TOAST_MARGIN
    elif 'Left' in position:
        x = win_x + TOAST_MARGIN
    else:
        x = win_x + (win_w - toast_w) // 2

    if 'Bottom' in position:
        y = (
            win_y + win_h - TOAST_H - TOAST_MARGIN
            - index * (TOAST_H + TOAST_SPACING)
        )
    else:
        y = (
            win_y + TOAST_MARGIN
            + index * (TOAST_H + TOAST_SPACING)
        )
    return x, y


def _ellipsize_text(message, font, max_width):
    if font.measure(message) <= max_width:
        return message

    ellipsis = "..."
    if font.measure(ellipsis) >= max_width:
        return ellipsis

    low = 0
    high = len(message)
    while low < high:
        mid = (low + high + 1) // 2
        candidate = message[:mid].rstrip() + ellipsis
        if font.measure(candidate) <= max_width:
            low = mid
        else:
            high = mid - 1
    return message[:low].rstrip() + ellipsis


def _toast_start(position, target_x, target_y):
    offset = TOAST_SLIDE_OFFSET
    if 'Right' in position:
        return target_x + offset, target_y
    if 'Left' in position:
        return target_x - offset, target_y
    if position == 'Top-Center':
        return target_x, target_y - offset
    return target_x, target_y + offset


def _dismiss_toast(toast):
    position = getattr(toast, '_toast_position', None)
    if position is not None:
        stack = _toast_stacks.get(position, [])
        if toast in stack:
            stack.remove(toast)
    try:
        toast.destroy()
    except tk.TclError:
        pass

accents = {
    "info": "#4a9eff", 
    "success": "#6fcf6a", 
    "warning": "#e0a44a", 
    "error": "#d9534f"
}

CUTOFF = False

def show_toast(parent, message, type="info", accent=None, position='Bottom-Right', duration=TOAST_HOLD_MS, SHOW_TOOLTIP=False):
    global CUTOFF
    if SHOW_TOOLTIP:
        CUTOFF = True
    global TOAST_HOLD_MS
    TOAST_HOLD_MS = duration
    global accents
    if accent == None:
        _accent = accents[type]
    else:
        _accent = accent
    stack = _toast_stacks.setdefault(position, [])
    message_font = tkfont.Font(family='Segoe UI', size=13, weight='bold')
    parent.update_idletasks()
    max_available_width = min(
        TOAST_MAX_W,
        max(parent.winfo_width() - (TOAST_MARGIN * 2), TOAST_MIN_W),
    )
    message_width = message_font.measure(message)
    toast_w = min(
        max(message_width + TOAST_HORIZONTAL_CHROME, TOAST_MIN_W),
        max_available_width,
    )
    message_max_width = max(toast_w - TOAST_HORIZONTAL_CHROME, 1)
    display_message = _ellipsize_text(message, message_font, message_max_width)
    if '...' in display_message:
        CUTOFF = True
        if duration == TOAST_HOLD_MS:
            TOAST_HOLD_MS = 6000
    used = {
        t._toast_index for t in stack if hasattr(t, '_toast_index')
    }
    index = 0
    while index in used:
        index += 1

    target_x, target_y = _toast_slot(parent, position, index, toast_w)
    start_x, start_y = _toast_start(position, target_x, target_y)

    toast = tk.Toplevel(parent)
    if CUTOFF:
        CTkToolTip(
            toast,
            message=message,
            text_color=_accent,
            always_on_top=True,
        )
    toast.overrideredirect(True)
    toast.attributes('-alpha', 0.0)
    toast.attributes('-topmost', True)
    toast.configure(bg='#3c3c3c')
    toast._toast_index = index
    toast._toast_position = position

    inner = tk.Frame(toast, bg='#252526')
    inner.pack(fill='both', expand=True, padx=1, pady=1)
    tk.Frame(inner, bg=_accent, width=4).pack(side='left', fill='y')
    ctk.CTkLabel(
        inner, text=display_message,
        font=('Segoe UI', 13, 'bold'),
        text_color=_accent, anchor='w', fg_color='#252526',
    ).pack(side='left', padx=12, pady=10, fill='both', expand=True)

    toast.geometry(f'{toast_w}x{TOAST_H}+{start_x}+{start_y}')
    stack.append(toast)

    def slide_in(t):
        cx = int(lerp(start_x, target_x, t))
        cy = int(lerp(start_y, target_y, t))
        toast.geometry(f'{toast_w}x{TOAST_H}+{cx}+{cy}')
        toast.attributes('-alpha', min(t * 1.5, 1.0))

    def slide_out():
        out_x, out_y = _toast_start(position, target_x, target_y)

        def step(t):
            cx = int(lerp(target_x, out_x, t))
            cy = int(lerp(target_y, out_y, t))
            toast.geometry(f'{toast_w}x{TOAST_H}+{cx}+{cy}')
            toast.attributes('-alpha', 1 - t)

        Tween(
            toast, 0.3, ease_in, step,
            on_done=lambda: _dismiss_toast(toast),
        ).start()

    Tween(
        toast, 0.7, back_out, slide_in,
        on_done=lambda: toast.after(TOAST_HOLD_MS, slide_out),
    ).start()
    return toast

if __name__ == "__main__":
    ctk.set_appearance_mode('dark')
    app = ctk.CTk()
    app.geometry('600x320')
    entry = ctk.CTkEntry(app, placeholder_text='Enter text for toast notification')
    entry.pack(fill='x', padx=10, pady=10)
    dropdown = ctk.CTkOptionMenu(app, values=[value.capitalize() for value in accents.keys()])
    dropdown.pack(fill='x', padx=10, pady=10)
    ctk.CTkButton(
        app, text='Show Toast',
        command=lambda: show_toast(app, entry.get() or dropdown.get()+': this is a toast demo', dropdown.get().lower()),
    ).pack(fill='both', expand=True, padx=10, pady=10)
    app.mainloop()
